/** Isolated regression for bank statement import and reconciliation. */
'use strict';
const fs=require('fs'),os=require('os'),path=require('path'),http=require('http');
process.env.DATA_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'tdos-banking-'));process.env.AUTO_SEED='true';process.env.JWT_SECRET='banking-test-secret-that-is-longer-than-32-characters';process.env.NODE_ENV='test';process.env.INITIAL_SUPERADMIN_PASSWORD='TestSuperAdmin@123';process.env.INITIAL_STAFF_PASSWORD='TestStaffAccount@123';
const app=require('./server'),store=require('./db/store');let passed=0,failed=0,port;
function request(method,requestPath,body,cookie){return new Promise((resolve,reject)=>{const payload=body==null?null:Buffer.from(JSON.stringify(body));const req=http.request({host:'127.0.0.1',port,path:requestPath,method,headers:{...(payload?{'Content-Type':'application/json','Content-Length':payload.length}:{}),...(cookie?{Cookie:cookie}:{})}},res=>{const chunks=[];res.on('data',chunk=>chunks.push(chunk));res.on('end',()=>{const buffer=Buffer.concat(chunks);let json={};try{json=JSON.parse(buffer.toString())}catch(_){}resolve({status:res.statusCode,json,cookie:res.headers['set-cookie']?.[0]?.split(';')[0]||cookie});});});req.on('error',reject);if(payload)req.write(payload);req.end();});}
function check(name,condition,extra){if(condition){passed++;console.log('  PASS  '+name);}else{failed++;console.log('  FAIL  '+name+(extra?' -> '+JSON.stringify(extra).slice(0,250):''));}}
async function run(){await app.ready;const server=app.listen(0);await new Promise(resolve=>server.once('listening',resolve));port=server.address().port;console.log('\n=== Tech Defenders OS banking regression ===\n');try{
 let response=await request('GET','/api/finance-controls/bank-reconciliation');check('banking endpoints require authentication',response.status===401);
 response=await request('POST','/api/auth/login',{email:'admin@techdefenders.in',password:'TestStaffAccount@123'});const cookie=response.cookie,org=store.find('organizations')[0];check('administrator login works',response.status===200&&!!cookie);
 response=await request('POST','/api/finance-controls/bank-accounts',{name:'Main current account',bankName:'Test Bank',accountNumber:'1234567890',ifsc:'TEST0001',openingBalance:1000},cookie);const account=response.json.account;check('bank account is created',response.status===201&&account?.bankName==='Test Bank');
 const customer=store.insert('customers',{orgId:org.id,name:'Banking Customer'}),supplier=store.insert('suppliers',{orgId:org.id,name:'Banking Supplier'});
 const receipt=store.insert('receipts',{orgId:org.id,customerId:customer.id,number:'REC-BANK',date:'2026-09-19',amount:5000});
 const payment=store.insert('supplierPayments',{orgId:org.id,supplierId:supplier.id,number:'PAY-BANK',date:'2026-09-19',amount:2200});
 const rows=[{date:'2026-09-19',description:'Customer receipt',reference:'REC-BANK',debit:'',credit:'5000',balance:'6000'},{date:'2026-09-19',description:'Supplier payment',reference:'PAY-BANK',debit:'2200',credit:'',balance:'3800'},{date:'2026-09-20',description:'Bank charge',reference:'CHARGE',debit:'100',credit:'',balance:'3700'}];
 response=await request('POST','/api/finance-controls/bank-statements/import',{bankAccountId:account.id,fileName:'statement.csv',rows},cookie);check('statement import auto-matches receipts and supplier payments',response.status===201&&response.json.summary?.imported===3&&response.json.summary?.autoMatched===2,response.json);
 response=await request('POST','/api/finance-controls/bank-statements/import',{bankAccountId:account.id,fileName:'statement.csv',rows},cookie);check('duplicate bank rows are ignored',response.status===201&&response.json.summary?.duplicates===3);
 response=await request('GET','/api/finance-controls/bank-reconciliation?bankAccountId='+account.id,null,cookie);const unmatched=response.json.transactions.find(row=>row.status==='unmatched');check('reconciliation separates unmatched transactions',response.status===200&&response.json.summary?.matched===2&&response.json.summary?.unmatched===1&&!!unmatched,response.json);
 const expense=store.insert('expenses',{orgId:org.id,number:'EXP-BANK',date:'2026-09-20',amount:100,status:'approved'});
 response=await request('POST','/api/finance-controls/bank-transactions/'+unmatched.id+'/match',{matchedType:'expense',matchedId:expense.id},cookie);check('manual matching links a valid finance record',response.status===200&&response.json.transaction?.status==='matched');
 response=await request('POST','/api/finance-controls/bank-transactions/'+unmatched.id+'/unmatch',{},cookie);check('matched transaction can be safely unmatched',response.status===200&&response.json.transaction?.status==='unmatched');
 response=await request('POST','/api/finance-controls/bank-reconciliation/close',{bankAccountId:account.id,periodEnd:'2026-09-30',statementBalance:3700},cookie);check('reconciliation blocks unexplained transactions',response.status===409);
 response=await request('POST','/api/finance-controls/bank-reconciliation/close',{bankAccountId:account.id,periodEnd:'2026-09-30',statementBalance:3700,allowUnmatched:true},cookie);check('authorized close stores exception count',response.status===201&&response.json.reconciliation?.unmatchedCount===1);
 check('matching references are written back to payment records',store.byId('receipts',receipt.id)?.reconciliationStatus==='matched'&&store.byId('supplierPayments',payment.id)?.reconciliationStatus==='matched');await store.flush();
 }finally{await new Promise(resolve=>server.close(resolve));await store.close().catch(()=>{});}console.log(`\n=== Results: ${passed} passed, ${failed} failed ===\n`);if(failed)process.exitCode=1;}
run().catch(error=>{console.error(error);process.exitCode=1;});
