'use strict';const express=require('express'),crypto=require('crypto'),store=require('../../db/store');const{requireAuth,requirePerm}=require('../middleware');const{audit,r2,nextNumber}=require('../util');const router=express.Router();router.use(requireAuth);const clean=(v,m=240)=>String(v||'').trim().slice(0,m),hash=v=>crypto.createHash('sha256').update(v).digest('hex');

/* API keys/webhooks: raw credentials are returned once and never persisted. */
router.get('/api-hub',requirePerm('admin','view'),(req,res)=>res.json({keys:store.find('apiKeys',x=>x.orgId===req.org.id).map(({keyHash,...x})=>x),webhooks:store.find('apiWebhooks',x=>x.orgId===req.org.id).map(({secretHash,...x})=>x),logs:store.find('apiRequestLogs',x=>x.orgId===req.org.id).slice(-100).reverse(),connectors:store.find('integrationConfigs',x=>x.orgId===req.org.id).map(({credentials,...x})=>({...x,configured:Boolean(credentials)}))}));
router.post('/api-keys',requirePerm('admin','edit'),(req,res)=>{const name=clean(req.body?.name,100),scopes=Array.isArray(req.body?.scopes)?req.body.scopes.filter(x=>['read','write','webhook'].includes(x)):['read'];if(!name)return res.status(400).json({error:'API key name is required'});const raw='tdos_'+crypto.randomBytes(30).toString('base64url'),prefix=raw.slice(0,12),key=store.insert('apiKeys',{orgId:req.org.id,name,prefix,keyHash:hash(raw),scopes:[...new Set(scopes)],status:'active',lastUsedAt:null,createdBy:req.user.id});audit(req.org.id,req.user.id,'create','api_key',key.id,{name,scopes:key.scopes});const{keyHash,...safe}=key;res.status(201).json({apiKey:safe,secret:raw});});
router.post('/api-keys/:id/revoke',requirePerm('admin','edit'),(req,res)=>{const key=store.findOne('apiKeys',x=>x.id===req.params.id&&x.orgId===req.org.id);if(!key)return res.status(404).json({error:'API key not found'});const updated=store.update('apiKeys',key.id,{status:'revoked',revokedAt:new Date().toISOString(),revokedBy:req.user.id});audit(req.org.id,req.user.id,'revoke','api_key',key.id,{});const{keyHash,...safe}=updated;res.json({apiKey:safe});});
router.post('/webhooks',requirePerm('admin','edit'),(req,res)=>{const name=clean(req.body?.name,100),url=clean(req.body?.url,500),events=Array.isArray(req.body?.events)?req.body.events.map(x=>clean(x,80)).filter(Boolean):[];if(!name||!/^https:\/\//i.test(url)||!events.length)return res.status(400).json({error:'Name, HTTPS URL and at least one event are required'});const secret=crypto.randomBytes(32).toString('hex'),hook=store.insert('apiWebhooks',{orgId:req.org.id,name,url,events,secretHash:hash(secret),status:'active',successCount:0,failureCount:0,createdBy:req.user.id});audit(req.org.id,req.user.id,'create','api_webhook',hook.id,{name,events});const{secretHash,...safe}=hook;res.status(201).json({webhook:safe,signingSecret:secret});});

/* Allow-listed report builder; no user SQL or arbitrary collection access. */
const DATASETS={customers:{collection:'customers',fields:['name','email','phone','stateCode','creditLimit','createdAt']},invoices:{collection:'invoices',fields:['number','date','dueDate','status','customerId','paidAmount','createdAt']},products:{collection:'products',fields:['sku','name','category','balance','minStock','salePrice','createdAt']},tickets:{collection:'tickets',fields:['number','subject','priority','status','customerId','assignedTo','createdAt']},purchase_orders:{collection:'purchaseOrders',fields:['number','date','status','supplierId','total','createdAt']}};
router.get('/reports',requirePerm('reports','view'),(req,res)=>res.json({reports:store.find('customReports',x=>x.orgId===req.org.id),datasets:Object.fromEntries(Object.entries(DATASETS).map(([k,v])=>[k,v.fields]))}));
router.post('/reports',requirePerm('reports','edit'),(req,res)=>{const dataset=DATASETS[req.body?.dataset],name=clean(req.body?.name,120);if(!dataset||!name)return res.status(400).json({error:'Report name and supported dataset are required'});const columns=(req.body?.columns||[]).filter(x=>dataset.fields.includes(x));if(!columns.length)return res.status(400).json({error:'Select at least one report column'});const report=store.insert('customReports',{orgId:req.org.id,name,dataset:req.body.dataset,columns,filters:Array.isArray(req.body?.filters)?req.body.filters.slice(0,10):[],groupBy:dataset.fields.includes(req.body?.groupBy)?req.body.groupBy:null,schedule:clean(req.body?.schedule,40)||null,createdBy:req.user.id});audit(req.org.id,req.user.id,'create','custom_report',report.id,{dataset:report.dataset});res.status(201).json({report});});
router.get('/reports/:id/run',requirePerm('reports','view'),(req,res)=>{const report=store.findOne('customReports',x=>x.id===req.params.id&&x.orgId===req.org.id);if(!report)return res.status(404).json({error:'Report not found'});const config=DATASETS[report.dataset];let rows=store.find(config.collection,x=>x.orgId===req.org.id);for(const f of report.filters||[]){if(!config.fields.includes(f.field))continue;const value=String(f.value??'').toLowerCase();rows=rows.filter(row=>f.operator==='equals'?String(row[f.field]??'').toLowerCase()===value:String(row[f.field]??'').toLowerCase().includes(value));}rows=rows.slice(0,5000).map(row=>Object.fromEntries(report.columns.map(key=>[key,row[key]??null])));let groups=null;if(report.groupBy)groups=Object.entries(rows.reduce((m,row)=>(m[String(row[report.groupBy]??'Unspecified')]=(m[String(row[report.groupBy]??'Unspecified')]||0)+1,m),{})).map(([label,count])=>({label,count}));audit(req.org.id,req.user.id,'run','custom_report',report.id,{rows:rows.length});res.json({report,rows,groups,total:rows.length});});

/* Communication governance: segmentation, channel consent and template review. */
router.get('/communication',requirePerm('communication','view'),(req,res)=>res.json({segments:store.find('communicationSegments',x=>x.orgId===req.org.id),consents:store.find('communicationConsents',x=>x.orgId===req.org.id),approvals:store.find('templateApprovals',x=>x.orgId===req.org.id),inbound:store.find('inboundCommunications',x=>x.orgId===req.org.id).slice(-200).reverse()}));
router.post('/communication/segments',requirePerm('communication','edit'),(req,res)=>{const name=clean(req.body?.name,100);if(!name)return res.status(400).json({error:'Segment name is required'});const item=store.insert('communicationSegments',{orgId:req.org.id,name,channel:['email','sms','whatsapp'].includes(req.body?.channel)?req.body.channel:'email',criteria:{stateCode:clean(req.body?.stateCode,10),customerHealth:clean(req.body?.customerHealth,30)},active:true});audit(req.org.id,req.user.id,'create','communication_segment',item.id,{name});res.status(201).json({segment:item});});
router.post('/communication/consents',requirePerm('communication','edit'),(req,res)=>{const customer=store.findOne('customers',x=>x.id===req.body?.customerId&&x.orgId===req.org.id),channel=req.body?.channel;if(!customer||!['email','sms','whatsapp'].includes(channel))return res.status(400).json({error:'Customer and valid channel are required'});const existing=store.findOne('communicationConsents',x=>x.orgId===req.org.id&&x.customerId===customer.id&&x.channel===channel),patch={status:req.body?.status==='opted_out'?'opted_out':'opted_in',source:clean(req.body?.source,80)||'manual',recordedAt:new Date().toISOString(),recordedBy:req.user.id},item=existing?store.update('communicationConsents',existing.id,patch):store.insert('communicationConsents',{orgId:req.org.id,customerId:customer.id,customerName:customer.name,channel,...patch});audit(req.org.id,req.user.id,'record','communication_consent',item.id,{channel,status:item.status});res.json({consent:item});});
router.post('/communication/templates/:id/decision',requirePerm('communication','approve'),(req,res)=>{const template=store.findOne('emailTemplates',x=>x.id===req.params.id&&x.orgId===req.org.id);if(!template)return res.status(404).json({error:'Template not found'});const decision=req.body?.decision==='rejected'?'rejected':'approved',approval=store.insert('templateApprovals',{orgId:req.org.id,templateId:template.id,decision,note:clean(req.body?.note,500),decidedBy:req.user.id,decidedAt:new Date().toISOString()});store.update('emailTemplates',template.id,{approvalStatus:decision});audit(req.org.id,req.user.id,decision,'email_template',template.id,{});res.json({approval});});

/* B2B catalogue and order workflow with customer-specific prices. */
router.get('/commerce',requirePerm('sales','view'),(req,res)=>res.json({catalogs:store.find('commerceCatalogs',x=>x.orgId===req.org.id),prices:store.find('commercePrices',x=>x.orgId===req.org.id),orders:store.find('commerceOrders',x=>x.orgId===req.org.id)}));
router.post('/commerce/catalogs',requirePerm('sales','edit'),(req,res)=>{const name=clean(req.body?.name,120),productIds=(req.body?.productIds||[]).filter(id=>store.findOne('products',x=>x.id===id&&x.orgId===req.org.id));if(!name||!productIds.length)return res.status(400).json({error:'Catalogue name and products are required'});const item=store.insert('commerceCatalogs',{orgId:req.org.id,name,productIds,status:'active',createdBy:req.user.id});audit(req.org.id,req.user.id,'create','commerce_catalog',item.id,{name});res.status(201).json({catalog:item});});
router.post('/commerce/prices',requirePerm('sales','edit'),(req,res)=>{const customer=store.findOne('customers',x=>x.id===req.body?.customerId&&x.orgId===req.org.id),product=store.findOne('products',x=>x.id===req.body?.productId&&x.orgId===req.org.id),price=r2(Number(req.body?.price)||0);if(!customer||!product||price<=0)return res.status(400).json({error:'Customer, product and positive price are required'});const item=store.insert('commercePrices',{orgId:req.org.id,customerId:customer.id,customerName:customer.name,productId:product.id,productName:product.name,price,validUntil:clean(req.body?.validUntil,10)||null});audit(req.org.id,req.user.id,'create','commerce_price',item.id,{customerId:customer.id,productId:product.id});res.status(201).json({price:item});});
router.post('/commerce/orders',requirePerm('sales','create'),(req,res)=>{const customer=store.findOne('customers',x=>x.id===req.body?.customerId&&x.orgId===req.org.id),lines=Array.isArray(req.body?.lines)?req.body.lines:[];if(!customer||!lines.length)return res.status(400).json({error:'Customer and order lines are required'});const normalized=[];for(const line of lines){const product=store.findOne('products',x=>x.id===line.productId&&x.orgId===req.org.id),qty=r2(Number(line.qty)||0);if(!product||qty<=0)return res.status(400).json({error:'Every order line needs a valid product and quantity'});const special=store.findOne('commercePrices',x=>x.orgId===req.org.id&&x.customerId===customer.id&&x.productId===product.id&&(!x.validUntil||x.validUntil>=new Date().toISOString().slice(0,10))),rate=r2(Number(special?.price??product.salePrice)||0);normalized.push({productId:product.id,name:product.name,qty,rate,lineTotal:r2(qty*rate)});}const total=r2(normalized.reduce((s,x)=>s+x.lineTotal,0)),order=store.insert('commerceOrders',{orgId:req.org.id,number:nextNumber(req.org.id,'commerceOrder'),customerId:customer.id,customerName:customer.name,lines:normalized,total,status:req.body?.requiresApproval?'pending_approval':'confirmed',createdBy:req.user.id});audit(req.org.id,req.user.id,'create','commerce_order',order.id,{customerId:customer.id,total});res.status(201).json({order});});
router.post('/commerce/orders/:id/convert',requirePerm('sales','edit'),(req,res)=>{const order=store.findOne('commerceOrders',x=>x.id===req.params.id&&x.orgId===req.org.id);if(!order)return res.status(404).json({error:'Commerce order not found'});if(order.salesOrderId)return res.status(409).json({error:'Order already converted'});const salesOrder=store.insert('salesOrders',{orgId:req.org.id,number:nextNumber(req.org.id,'salesOrder'),customerId:order.customerId,date:new Date().toISOString().slice(0,10),status:'confirmed',lines:order.lines,totals:{grandTotal:order.total},source:'b2b_commerce'});store.update('commerceOrders',order.id,{status:'converted',salesOrderId:salesOrder.id});audit(req.org.id,req.user.id,'convert','commerce_order',order.id,{salesOrderId:salesOrder.id});res.json({salesOrder});});
module.exports=router;
